-- SPDX-FileCopyrightText: (C) 2025 NetKnights GmbH <https://netknights.it>
-- SPDX-License-Identifier: AGPL-3.0-or-later
--
-- Database migration: Add Device Management Tables
-- 
-- This migration adds support for device management and 2FA device activation
-- with database persistence to prevent data loss during recovery scenarios.

-- Create Device table
CREATE TABLE IF NOT EXISTS device (
    "Id" SERIAL PRIMARY KEY,
    "DeviceId" VARCHAR(255) NOT NULL UNIQUE,
    "DeviceName" VARCHAR(255) NOT NULL DEFAULT '',
    "Platform" VARCHAR(50) NOT NULL DEFAULT '',
    "OsVersion" VARCHAR(100) NOT NULL DEFAULT '',
    "Model" VARCHAR(255) NOT NULL DEFAULT '',
    "RegisteredAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "IsActivated" BOOLEAN NOT NULL DEFAULT FALSE,
    "ActivatedAt" TIMESTAMP NULL,
    "ActivationToken" VARCHAR(255) NULL
);

-- Create indexes for Device table
CREATE INDEX IF NOT EXISTS "IX_device_DeviceId" ON device("DeviceId");
CREATE INDEX IF NOT EXISTS "IX_device_IsActivated" ON device("IsActivated");

-- Create PendingDeviceActivation table
CREATE TABLE IF NOT EXISTS pending_device_activation (
    "Id" SERIAL PRIMARY KEY,
    "DeviceId" VARCHAR(255) NOT NULL UNIQUE,
    "Secret" VARCHAR(500) NOT NULL,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ExpiresAt" TIMESTAMP NOT NULL
);

-- Create indexes for PendingDeviceActivation table
CREATE INDEX IF NOT EXISTS "IX_pending_device_activation_DeviceId" ON pending_device_activation("DeviceId");
CREATE INDEX IF NOT EXISTS "IX_pending_device_activation_ExpiresAt" ON pending_device_activation("ExpiresAt");

-- Add comments for documentation
COMMENT ON TABLE device IS 'Stores registered devices for 2FA activation and management';
COMMENT ON COLUMN device."DeviceId" IS 'Unique device identifier generated by client';
COMMENT ON COLUMN device."IsActivated" IS 'Whether the device has been activated via OTP';
COMMENT ON COLUMN device."ActivationToken" IS 'Unique activation token (UUID)';

COMMENT ON TABLE pending_device_activation IS 'Stores temporary activation requests with expiration (typically 5 minutes)';
COMMENT ON COLUMN pending_device_activation."Secret" IS 'Base32-encoded secret for OTP generation';
COMMENT ON COLUMN pending_device_activation."ExpiresAt" IS 'Expiration time for this activation request';
