// SPDX-FileCopyrightText: (C) 2025 NetKnights GmbH <https://netknights.it>
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// Device management database models for 2FA device activation and tracking

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace PrivacyIdeaServer.Models.Database
{
    /// <summary>
    /// Represents a registered device in the system
    /// Stores device information for 2FA activation and management
    /// </summary>
    [Table("device")]
    [Index(nameof(DeviceId), IsUnique = true)]
    [Index(nameof(IsActivated))]
    public class Device : IMethodsMixin
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        int? IMethodsMixin.Id => Id;

        /// <summary>
        /// Unique device identifier (generated by client)
        /// </summary>
        [Required]
        [StringLength(255)]
        public string DeviceId { get; set; } = string.Empty;

        /// <summary>
        /// Human-readable device name
        /// </summary>
        [StringLength(255)]
        public string DeviceName { get; set; } = string.Empty;

        /// <summary>
        /// Device platform (iOS, Android, Web, etc.)
        /// </summary>
        [StringLength(50)]
        public string Platform { get; set; } = string.Empty;

        /// <summary>
        /// Operating system version
        /// </summary>
        [StringLength(100)]
        public string OsVersion { get; set; } = string.Empty;

        /// <summary>
        /// Device model information
        /// </summary>
        [StringLength(255)]
        public string Model { get; set; } = string.Empty;

        /// <summary>
        /// Date and time when device was first registered
        /// </summary>
        [Required]
        public DateTime RegisteredAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Whether the device has been activated
        /// </summary>
        [Required]
        public bool IsActivated { get; set; } = false;

        /// <summary>
        /// Date and time when device was activated
        /// </summary>
        public DateTime? ActivatedAt { get; set; }

        /// <summary>
        /// Unique activation token (UUID)
        /// </summary>
        [StringLength(255)]
        public string? ActivationToken { get; set; }

        public Device()
        {
        }

        public Device(string deviceId, string deviceName, string platform, string osVersion, string model)
        {
            DeviceId = deviceId;
            DeviceName = deviceName;
            Platform = platform;
            OsVersion = osVersion;
            Model = model;
            RegisteredAt = DateTime.UtcNow;
            IsActivated = false;
        }
    }

    /// <summary>
    /// Represents a pending device activation request
    /// Stores temporary activation data with expiration
    /// </summary>
    [Table("pending_device_activation")]
    [Index(nameof(DeviceId), IsUnique = true)]
    [Index(nameof(ExpiresAt))]
    public class PendingDeviceActivation : IMethodsMixin
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        int? IMethodsMixin.Id => Id;

        /// <summary>
        /// Device identifier for this activation request
        /// </summary>
        [Required]
        [StringLength(255)]
        public string DeviceId { get; set; } = string.Empty;

        /// <summary>
        /// Secret key for OTP generation (Base32 encoded)
        /// </summary>
        [Required]
        [StringLength(500)]
        public string Secret { get; set; } = string.Empty;

        /// <summary>
        /// Date and time when this activation request was created
        /// </summary>
        [Required]
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Date and time when this activation request expires
        /// Typically 5 minutes after creation
        /// </summary>
        [Required]
        public DateTime ExpiresAt { get; set; }

        public PendingDeviceActivation()
        {
        }

        public PendingDeviceActivation(string deviceId, string secret, DateTime expiresAt)
        {
            DeviceId = deviceId;
            Secret = secret;
            CreatedAt = DateTime.UtcNow;
            ExpiresAt = expiresAt;
        }
    }
}
